### ISSUE TITLE
Setting IccMax?

### ISSUE THREAD

**Issue by arter97** [erpalma/throttled#97]
For most 8th Gen laptops I've seen, IccMax is still a big factor on why the processor is throttling. (And I think lifting up IccMax throttling should be the next milestone for this project as well.)

As an example, the LG Gram(8250U), suffers from current limit throttling if IccMax is left as default.
This prevents hitting 3.4 GHz on all cores, even after setting HWP bias to "performance".

I've done a fair bit of research, but I could not find any solid information on setting IccMax via MSR register or MMIO access.

**Comment by DEvil0000** [comment]
you never now if a current limit is there for a reason (and it most likely is). changeing this will put the laptop in danger for hardware damage (short or longterm) or in the worst case catching fire.I can think of a ton of different reasons for setting a current limit.

**Comment by arter97** [comment]
So is every other throttling, though.

**Comment by DEvil0000** [comment]
thats not true. more current has way more danger.

-------- Ursprüngliche Nachricht --------
Von: Park Ju Hyung <notifications@github.com> 
Datum: 09.02.2019  08:30  (GMT+01:00) 
An: erpalma/throttled <throttled@noreply.github.com> 
Cc: "A. Binzxxxxxx" <alexander@binzberger.de>, Comment <comment@noreply.github.com> 
Betreff: Re: [erpalma/throttled] Setting IccMax? (#97) 

So is every other throttling, though.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/erpalma/throttled","title":"erpalma/throttled","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/erpalma/throttled"}},"updates":{"snippets":[{"icon":"PERSON","message":"@arter97 in #97: So is every other throttling, though."}],"action":{"name":"View Issue","url":"https://github.com/erpalma/throttled/issues/97#issuecomment-462021959"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/erpalma/throttled/issues/97#issuecomment-462021959",
"url": "https://github.com/erpalma/throttled/issues/97#issuecomment-462021959",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by arter97** [comment]
Well, that's what I thought https://github.com/erpalma/throttled/blob/master/README.md#disclaimer was for.

Nvm, got a reply from the ThrottleStop's author.

Thanks.

**Comment by ejgallego** [comment]
> Nvm, got a reply from the ThrottleStop's author.

Could you share what the reply was? Thanks!

**Comment by arter97** [comment]
Figured it out.

On Windows:
Wrmsr(0x150, dwIccMax, 0x80000017 | (dwAgent << 8));
dwAgent is 0 for CPU Core, 1 for iGPU and 2 for CPU Cache.
Command 17 is to write IccMax to the register and command 16 is how you read IccMax from the register.

0x3ff is the max on my 8250U(this would be likely for every other CPUs), so I'm using the following commands:
wrmsr -a 0x150 0x80000017000003ff
wrmsr -a 0x150 0x80000117000003ff
wrmsr -a 0x150 0x80000217000003ff

**Comment by ejgallego** [comment]
Thanks @arter97 , is there some more information about the risks of current modification?

**Comment by arter97** [comment]
There's a plenty of discussion of that on the ThrottleStop's thread.

You can use the search feature on that forum to find more information.

**Comment by erpalma** [comment]
I can implement this in the tool and I might add a big warning when IccMax is overridden. 

Clearly the risk of raising this value is a physical damage both to the voltage regulators and the CPU either due to higher temperatures or currents above the absolute maximum ratings of the component.

**Comment by erpalma** [comment]
I'm still missing the formula for calculate current given the value in the register (and vice versa)

**Comment by erpalma** [comment]
Added in master!
